ActionManager {
 Actions {
  Action Clutch_X {
   Type AnalogRelative
   InputSource InputSourceValue "{6870B885735889C4}" {
    Input "mouse:x_rel"
    Filter InputFilterValue "{6870B885467E5DF1}" {
    }
   }
  }
  Action Clutch_Y {
   Type AnalogRelative
   InputSource InputSourceValue "{6870B885574827FA}" {
    Input "mouse:y_rel"
   }
  }
  Action Clutch_Engage {
   Type Digital
   InputSource InputSourceValue "{6870B88535ECFEFF}" {
    Input "keyboard:KC_LCONTROL"
    Filter InputFilterHold "{687126DB649258F7}" {
     Threshold 0.2
    }
   }
  }
 }
 Contexts {
  ActionContext CarContext {
   ActionRefs +{
    "Clutch_Engage"
   }
  }
  ActionContext Clutch_Context {
   Priority 50
   Flags 0xa 0
   ActionRefs {
    "Clutch_X"
    "Clutch_Y"
    "Clutch_Engage"
   }
  }
 }
}